name: Cloudflare Tunnel

on:
  workflow_dispatch: # Executa manualmente
  push:
    branches:
      - main

jobs:
  cloudflare-tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Authenticate cloudflared
        run: cloudflared tunnel login --token ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Run tunnel
        run: cloudflared tunnel run --token eyJhIjoiNWQ1OWI0ZjdiZjIxNzgyMTMyOGNlZWFlNmIyZjQyNmMiLCJ0IjoiZTliYmFkMDUtMjUwMS00MWMxLWJhNzYtYTkxNGI0N2UxODM3IiwicyI6Ill6WmtZMlEzTURVdE5XTTRNaTAwWkdZM0xUa3dNVFl0T1dObE9HVXlaV1E1WWpkaCJ9
